

export const ADD_PEDIDO = "ADD_PEDIDO";
export const RETRIEVE_PEDIDOS = "RETRIEVE_PEDIDOS";
export const UPDATE_PEDIDO = "UPDATE_PEDIDO";
export const DELETE_PEDIDO = "DELETE_PEDIDO";
export const DELETE_ALL_PEDIDOS = "DELETE_ALL_PEDIDOS";